[package]
name = "fisher"
version = "1.0.0-beta.7"
license = "GPL-3.0"

description = "Webhooks catcher written in Rust"
authors = ["Pietro Albini <pietro@pietroalbini.io>"]
readme = "README.md"

repository = "https://github.com/pietroalbini/fisher"

[[bin]]
name = "fisher"
doc = false

[dependencies]
url="^1.2"
ansi_term="^0.9"
regex="^0.2"
clap="^2.11"
lazy_static="^0.2"
rand="^0.3"
tiny_http="^0.5"
libc="^0.2"
signal="^0.3"
nix="^0.9"

serde="^1.0"
serde_derive="^1.0"
serde_json="^1.0"

# Dependencies for the "provider-github" feature
ring = { version="^0.11", optional=true }

# Clippy is optional
clippy = { version="^0.0", optional=true }

[dev-dependencies]
hyper="^0.10"

[features]
default = ["provider-github", "provider-gitlab"]

provider-github = ["ring"]
provider-gitlab = []

[profile.release]
lto = true

[workspace]
