---

site_name: Fisher documentation

pages:
  - "Home page": "index.md"
  - "Introduction":
    - "Why you should use Fisher": "why.md"
    - "Installing Fisher": "install.md"
  - "Tutorials":
    - "Automatic deploy from GitHub": "tutorial/auto-deploy.md"
    - "Send emails when scripts fails": "tutorial/failure-email.md"
  - "Features":
    - "Third-party providers": "features/providers.md"
  - "Reference":
    - "The fisher command": "cli.md"
    - "Configuration comments": "config-comments.md"
    - "Scripts execution context": "env.md"
  - "Supported providers":
    - "Standalone provider": "providers/standalone.md"
    - "GitHub provider": "providers/github.md"
    - "GitLab provider": "providers/gitlab.md"
  - "Other information":
    - "Changelog": "changelog.md"

theme: readthedocs
extra_css:
  - custom.css

docs_dir: src
theme_dir: theme
site_dir: build
